- hosts: apps
  become: yes
  tasks:
  - name: Installs nginx web server
    apt:
      name: nginx
      state: present
      update_cache: true
    notify:
    - start nginx

  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copy local-reverse-proxy.conf.j2
    template:
      src: local-reverse-proxy.conf.j2
      dest: /etc/nginx/sites-enabled/localproxy
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    - name: start nginx
      service:
        name: nginx
        state: started
