- hosts: apps
  become: yes
  vars_files:
    - vars/deploy-var.yaml
  tasks:
   - name: Get infos on container app{{ pre_version }}
     docker_container_info:
       name: app{{ pre_version }}
     register: result
   
   - name: reroute the local reverse proxy
     template:
       src: pre-local-reverse-proxy.conf.j2
       dest: /etc/nginx/sites-enabled/localproxy.conf
     when: result.exists == true
     notify: reload nginx

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

